#version: '3.8' # Specify a Compose file version
#
#services:
#  postgres:
#    image: postgres:latest  # Use the latest PostgreSQL image
#    restart: always
#    user: "501:501"
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data  # Persist data
#
#volumes:
#  postgres-data: # Named volume for data persistence

version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    user: "501:501"  # Add this if you need specific user permissions
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  tasks:
    build: .
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER} # Add your database credentials
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  postgres-data: